#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-scikit_build
Version  : 0.13.1
Release  : 6
URL      : https://files.pythonhosted.org/packages/a5/e6/2d32573ff027be7b9e9aec560afe2a20ffc4f9d631e69c5cce252695f33b/scikit-build-0.13.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a5/e6/2d32573ff027be7b9e9aec560afe2a20ffc4f9d631e69c5cce252695f33b/scikit-build-0.13.1.tar.gz
Summary  : Improved build system generator for Python C/C++/Fortran/Cython extensions
Group    : Development/Tools
License  : MIT NCSA
Requires: pypi-scikit_build-license = %{version}-%{release}
Requires: pypi-scikit_build-python = %{version}-%{release}
Requires: pypi-scikit_build-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : pypi(distro)
BuildRequires : pypi(packaging)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
===============================
scikit-build
===============================
Improved build system generator for CPython C/C++/Fortran/Cython extensions.

%package license
Summary: license components for the pypi-scikit_build package.
Group: Default

%description license
license components for the pypi-scikit_build package.


%package python
Summary: python components for the pypi-scikit_build package.
Group: Default
Requires: pypi-scikit_build-python3 = %{version}-%{release}

%description python
python components for the pypi-scikit_build package.


%package python3
Summary: python3 components for the pypi-scikit_build package.
Group: Default
Requires: python3-core
Provides: pypi(scikit_build)
Requires: pypi(distro)
Requires: pypi(packaging)
Requires: pypi(setuptools)
Requires: pypi(wheel)

%description python3
python3 components for the pypi-scikit_build package.


%prep
%setup -q -n scikit-build-0.13.1
cd %{_builddir}/scikit-build-0.13.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644280168
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-scikit_build
cp %{_builddir}/scikit-build-0.13.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-scikit_build/48d9b98c9f043b5a42399020beaac0aa6afbc4b3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-scikit_build/48d9b98c9f043b5a42399020beaac0aa6afbc4b3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
